
version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=wlu@2341
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: legal-notices
    restart: always
    ports: 
      - 3330:3330
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local