import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBarHome from '../components/navbar'
import { Card } from 'react-bootstrap';

const Home: NextPage = () => {
  return (
    <div >
      <NavBarHome />
      <Head>
        <title>Avisos Legais - Control Painel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Card>
        <Card.Header>
          <h1>Painel de Controle</h1>
        </Card.Header>
        <Card.Body>

          <h2>Pagina Inicial</h2>
        </Card.Body>
      </Card>
      </main>
    </div>
  )
}

export default Home
